### ISSUE TITLE
USER STORY: Navigation - Conditional rendering

### ISSUE THREAD

**Issue by JFrdrkssn** [JFrdrkssn/project-5#2]
As a **User** I can **clearly see if I'm logged in/out** so that **I can log/sign in/out**.

## Tasks

- [ ] Provide information in navbar on authentication status
- [ ] Provide information on pages where authentication is necessary
- [ ] Clear user authentication CTA across the site
