### ISSUE TITLE
USER STORY: Authentication - Sign up

### ISSUE THREAD

**Issue by JFrdrkssn** [JFrdrkssn/project-5#5]
As a **user** I can **create a new account** so that **I can access all the features for signed up users**.

## Tasks

- [ ] Provide sign up form and authentication
- [ ] Provide information on how to sign up
- [ ] Provide feedback for invalid form inputs
